<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Category extends Model
{
    use HasFactory;
    protected $table = 'categories';
    protected $fillable = [
        'parent_id',
        'name',
        'slug',
        'icon',
        'model_type'
    ];
    protected $hidden = ['created_at', 'updated_at'];
    public function parentCategory(){
        return $this->belongsTo(Category::class, 'parent_id');
    }

    public function childs():HasMany{
        return $this->hasMany(Category::class, 'parent_id');
    }

//    public function subCategories(): HasMany{
//        return $this->hasMany(Category::class, 'parent_id', 'id');
//    }
    public function deleteChildren(): void {
        foreach ($this->childs() as $child) {
            $child->deleteChildren();
            $child->delete();
        }
    }

    public static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($category){
            $category->deleteChildren();
        });
    }
}
